<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="A2ML30049" name="io.mosip.authentication.tests.DemographicAuthentication" tests="17" failures="0" timestamp="26 Jul 2019 06:31:58 GMT" time="142.204" errors="11">
  <testcase name="Authentication_Demographic_Address_With_primary and secondary lang_for VID_smoke_pos_38" time="6.333" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:191)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:46)
at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:12)
at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:17)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Address_With_primary and secondary lang_for VID_smoke_pos_38 -->
  <testcase name="Authentication_Demographic_Address_With_primary and secondary lang_smoke_pos_01" time="2.484" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:191)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:46)
at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:12)
at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:17)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Address_With_primary and secondary lang_smoke_pos_01 -->
  <testcase name="Authentication_Demographic_Address_With_secondary lang_smoke_pos_03" time="4.090" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:191)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:46)
at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:12)
at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:17)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Address_With_secondary lang_smoke_pos_03 -->
  <testcase name="Authentication_Demographic_Name_Male_Tittle_Normalisation_Smoke_For_UIN_Pos_01" time="2.054" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:191)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:46)
at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:12)
at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:17)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Name_Male_Tittle_Normalisation_Smoke_For_UIN_Pos_01 -->
  <testcase name="Authentication_Demographic_Address_With_primary lang_smoke_pos_02" time="16.854" classname="io.mosip.authentication.tests.DemographicAuthentication"/>
  <testcase name="Authentication_Demographic_Age_smoke_For IntegrationTest_UIN_Pos" time="13.561" classname="io.mosip.authentication.tests.DemographicAuthentication"/>
  <testcase name="Authentication_Demographic_Gender_With both language_smoke_For UIN_Pos_01" time="3.651" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:191)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:46)
at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:12)
at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:17)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Gender_With both language_smoke_For UIN_Pos_01 -->
  <testcase name="Authentication_Demographic_DateOfBirth_smoke_For IntegrationTest_UIN_Pos_01" time="22.101" classname="io.mosip.authentication.tests.DemographicAuthentication"/>
  <testcase name="Authentication_Demographic_fullAddress_With_primary lang_smoke_pos" time="5.087" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:191)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:46)
at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:12)
at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:17)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_fullAddress_With_primary lang_smoke_pos -->
  <testcase name="Authentication_Demographic_Gender_With_secondary_language_smoke_For UIN_Pos_02" time="4.539" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:191)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:46)
at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:12)
at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:17)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Gender_With_secondary_language_smoke_For UIN_Pos_02 -->
  <testcase name="Authentication_Demographic_EmailId_smoke_For IntegrationTest_UIN_Pos_01" time="15.775" classname="io.mosip.authentication.tests.DemographicAuthentication"/>
  <testcase name="Authentication_Demographic_fullAddress_With_secondary lang_smoke_pos" time="1.699" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:191)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:46)
at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:12)
at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:17)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_fullAddress_With_secondary lang_smoke_pos -->
  <testcase name="Authentication_Demographic_fullAddress_With_primary and secondary lang_smoke_pos" time="4.266" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:191)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:46)
at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:12)
at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:17)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_fullAddress_With_primary and secondary lang_smoke_pos -->
  <testcase name="Authentication_Demographic_Name_smoke_For UIN_Pos_01" time="2.264" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:191)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:46)
at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:12)
at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:17)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Name_smoke_For UIN_Pos_01 -->
  <testcase name="Authentication_Demographic_Name_WithSecLang_Smoke_For UIN_Pos" time="4.373" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:191)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:46)
at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:12)
at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:17)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Name_WithSecLang_Smoke_For UIN_Pos -->
  <testcase name="Authentication_Demographic_Gender_With_primary_language_smoke_For UIN_Pos_03" time="16.652" classname="io.mosip.authentication.tests.DemographicAuthentication"/>
  <testcase name="Authentication_Demographic_PhoneNumber_smoke_For IntegrationTest_UIN_Pos_01" time="16.421" classname="io.mosip.authentication.tests.DemographicAuthentication"/>
</testsuite> <!-- io.mosip.authentication.tests.DemographicAuthentication -->
